#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hellyon.Resource", IsApplication=true)]

namespace Hellyon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hellyon_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hellyon_logo_nobg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash_screen = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int actionsText = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int activePotsText = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int addFlowerImage = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int flowerImageView = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout1 = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int loginButton = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int newPotButton = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int password = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int passwordText = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int pot1Button = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int pot2Button = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int pot3Button = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int pot4Button = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int tableLayout1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow2 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow3 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow4 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow5 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int tableRow6 = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int textView10 = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int userName = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int userNameText = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OpenedPot = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PotActionPage = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int Actions = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int ActivePots = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Login = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int NewPot = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Password = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int Pot1 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Pot2 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Pot3 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Pot4 = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int Username = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button_text = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
